EYE_LOOK_IN_LEFT = "eyeLookInLeft"
EYE_LOOK_OUT_LEFT = "eyeLookOutLeft"
EYE_LOOK_DOWN_LEFT = "eyeLookDownLeft"
EYE_LOOK_UP_LEFT = "eyeLookUpLeft"
EYE_BLINK_LEFT = "eyeBlinkLeft"
EYE_SQUINT_LEFT = "eyeSquintLeft"
EYE_WIDE_LEFT = "eyeWideLeft"
EYE_LOOK_IN_RIGHT = "eyeLookInRight"
EYE_LOOK_OUT_RIGHT = "eyeLookOutRight"
EYE_LOOK_DOWN_RIGHT = "eyeLookDownRight"
EYE_LOOK_UP_RIGHT = "eyeLookUpRight"
EYE_BLINK_RIGHT = "eyeBlinkRight"
EYE_SQUINT_RIGHT = "eyeSquintRight"
EYE_WIDE_RIGHT = "eyeWideRight"
BROW_DOWN_LEFT = "browDownLeft"
BROW_OUTER_UP_LEFT = "browOuterUpLeft"
BROW_DOWN_RIGHT = "browDownRight"
BROW_OUTER_UP_RIGHT = "browOuterUpRight"
BROW_INNER_UP = "browInnerUp"
NOSE_SNEER_LEFT = "noseSneerLeft"
NOSE_SNEER_RIGHT = "noseSneerRight"
CHEEK_SQUINT_LEFT = "cheekSquintLeft"
CHEEK_SQUINT_RIGHT = "cheekSquintRight"
CHEEK_PUFF = "cheekPuff"
MOUTH_LEFT = "mouthLeft"
MOUTH_DIMPLE_LEFT = "mouthDimpleLeft"
MOUTH_FROWN_LEFT = "mouthFrownLeft"
MOUTH_LOWER_DOWN_LEFT = "mouthLowerDownLeft"
MOUTH_PRESS_LEFT = "mouthPressLeft"
MOUTH_SMILE_LEFT = "mouthSmileLeft"
MOUTH_STRETCH_LEFT = "mouthStretchLeft"
MOUTH_UPPER_UP_LEFT = "mouthUpperUpLeft"
MOUTH_RIGHT = "mouthRight"
MOUTH_DIMPLE_RIGHT = "mouthDimpleRight"
MOUTH_FROWN_RIGHT = "mouthFrownRight"
MOUTH_LOWER_DOWN_RIGHT = "mouthLowerDownRight"
MOUTH_PRESS_RIGHT = "mouthPressRight"
MOUTH_SMILE_RIGHT = "mouthSmileRight"
MOUTH_STRETCH_RIGHT = "mouthStretchRight"
MOUTH_UPPER_UP_RIGHT = "mouthUpperUpRight"
MOUTH_CLOSE = "mouthClose"
MOUTH_FUNNEL = "mouthFunnel"
MOUTH_PUCKER = "mouthPucker"
MOUTH_ROLL_LOWER = "mouthRollLower"
MOUTH_ROLL_UPPER = "mouthRollUpper"
MOUTH_SHRUG_LOWER = "mouthShrugLower"
MOUTH_SHRUG_UPPER = "mouthShrugUpper"
JAW_LEFT = "jawLeft"
JAW_RIGHT = "jawRight"
JAW_FORWARD = "jawForward"
JAW_OPEN = "jawOpen"
TONGUE_OUT = "tongueOut"

BLENDSHAPE_NAMES = [
    EYE_LOOK_IN_LEFT,  # 0
    EYE_LOOK_OUT_LEFT,  # 1
    EYE_LOOK_DOWN_LEFT,  # 2
    EYE_LOOK_UP_LEFT,  # 3
    EYE_BLINK_LEFT,  # 4
    EYE_SQUINT_LEFT,  # 5
    EYE_WIDE_LEFT,  # 6
    EYE_LOOK_IN_RIGHT,  # 7
    EYE_LOOK_OUT_RIGHT,  # 8
    EYE_LOOK_DOWN_RIGHT,  # 9
    EYE_LOOK_UP_RIGHT,  # 10
    EYE_BLINK_RIGHT,  # 11
    EYE_SQUINT_RIGHT,  # 12
    EYE_WIDE_RIGHT,  # 13
    BROW_DOWN_LEFT,  # 14
    BROW_OUTER_UP_LEFT,  # 15
    BROW_DOWN_RIGHT,  # 16
    BROW_OUTER_UP_RIGHT,  # 17
    BROW_INNER_UP,  # 18
    NOSE_SNEER_LEFT,  # 19
    NOSE_SNEER_RIGHT,  # 20
    CHEEK_SQUINT_LEFT,  # 21
    CHEEK_SQUINT_RIGHT,  # 22
    CHEEK_PUFF,  # 23
    MOUTH_LEFT,  # 24
    MOUTH_DIMPLE_LEFT,  # 25
    MOUTH_FROWN_LEFT,  # 26
    MOUTH_LOWER_DOWN_LEFT,  # 27
    MOUTH_PRESS_LEFT,  # 28
    MOUTH_SMILE_LEFT,  # 29
    MOUTH_STRETCH_LEFT,  # 30
    MOUTH_UPPER_UP_LEFT,  # 31
    MOUTH_RIGHT,  # 32
    MOUTH_DIMPLE_RIGHT,  # 33
    MOUTH_FROWN_RIGHT,  # 34
    MOUTH_LOWER_DOWN_RIGHT,  # 35
    MOUTH_PRESS_RIGHT,  # 36
    MOUTH_SMILE_RIGHT,  # 37
    MOUTH_STRETCH_RIGHT,  # 38
    MOUTH_UPPER_UP_RIGHT,  # 39
    MOUTH_CLOSE,  # 40
    MOUTH_FUNNEL,  # 41
    MOUTH_PUCKER,  # 42
    MOUTH_ROLL_LOWER,  # 43
    MOUTH_ROLL_UPPER,  # 44
    MOUTH_SHRUG_LOWER,  # 45
    MOUTH_SHRUG_UPPER,  # 46
    JAW_LEFT,  # 47
    JAW_RIGHT,  # 48
    JAW_FORWARD,  # 49
    JAW_OPEN,  # 50
    TONGUE_OUT,  # 51
]

EYE_LEFT_BLENDSHAPES = [
    EYE_LOOK_IN_LEFT,  # 0
    EYE_LOOK_OUT_LEFT,  # 1
    EYE_LOOK_DOWN_LEFT,  # 2
    EYE_LOOK_UP_LEFT,  # 3
    EYE_BLINK_LEFT,  # 4
    EYE_SQUINT_LEFT,  # 5
    EYE_WIDE_LEFT,  # 6
]

EYE_RIGHT_BLENDSHAPES = [
    EYE_LOOK_IN_RIGHT,  # 7
    EYE_LOOK_OUT_RIGHT,  # 8
    EYE_LOOK_DOWN_RIGHT,  # 9
    EYE_LOOK_UP_RIGHT,  # 10
    EYE_BLINK_RIGHT,  # 11
    EYE_SQUINT_RIGHT,  # 12
    EYE_WIDE_RIGHT,  # 13
]

BROW_LEFT_BLENDSHAPES = [
    BROW_DOWN_LEFT,  # 14
    BROW_OUTER_UP_LEFT,  # 15

]

BROW_RIGHT_BLENDSHAPES = [
    BROW_DOWN_RIGHT,  # 16
    BROW_OUTER_UP_RIGHT,  # 17

]

BROW_BOTH_BLENDSHAPES = [
    BROW_INNER_UP,  # 18
]

NOSE_BLENDSHAPES = [
    NOSE_SNEER_LEFT,  # 19
    NOSE_SNEER_RIGHT,  # 20
]

CHECK_BLENDSHAPES = [
    CHEEK_SQUINT_LEFT,  # 21
    CHEEK_SQUINT_RIGHT,  # 22
    CHEEK_PUFF,  # 23
]

MOUTH_LEFT_BLENDSHAPES = [
    MOUTH_LEFT,  # 24
    MOUTH_DIMPLE_LEFT,  # 25
    MOUTH_FROWN_LEFT,  # 26
    MOUTH_LOWER_DOWN_LEFT,  # 27
    MOUTH_PRESS_LEFT,  # 28
    MOUTH_SMILE_LEFT,  # 29
    MOUTH_STRETCH_LEFT,  # 30
    MOUTH_UPPER_UP_LEFT,  # 31
]

MOUTH_RIGHT_BLENDSHAPES = [
    MOUTH_RIGHT,  # 32
    MOUTH_DIMPLE_RIGHT,  # 33
    MOUTH_FROWN_RIGHT,  # 34
    MOUTH_LOWER_DOWN_RIGHT,  # 35
    MOUTH_PRESS_RIGHT,  # 36
    MOUTH_SMILE_RIGHT,  # 37
    MOUTH_STRETCH_RIGHT,  # 38
    MOUTH_UPPER_UP_RIGHT,  # 39
]

MOUTH_BOTH_BLENDSHAPES = [
    MOUTH_CLOSE,  # 40
    MOUTH_FUNNEL,  # 41
    MOUTH_PUCKER,  # 42
    MOUTH_ROLL_LOWER,  # 43
    MOUTH_ROLL_UPPER,  # 44
    MOUTH_SHRUG_LOWER,  # 45
    MOUTH_SHRUG_UPPER,  # 46
]

JAW_BLENDSHAPES = [
    JAW_LEFT,  # 47
    JAW_RIGHT,  # 48
    JAW_FORWARD,  # 49
    JAW_OPEN,  # 50
]

TONGUE_BLENDSHAPES = [
    TONGUE_OUT,  # 51
]

COLUMN_0_BLENDSHAPES = EYE_RIGHT_BLENDSHAPES + BROW_RIGHT_BLENDSHAPES + [NOSE_SNEER_RIGHT, CHEEK_SQUINT_RIGHT]
COLUMN_1_BLENDSHAPES = EYE_LEFT_BLENDSHAPES + BROW_LEFT_BLENDSHAPES + [NOSE_SNEER_LEFT, CHEEK_SQUINT_LEFT]
COLUMN_2_BLENDSHAPES = MOUTH_RIGHT_BLENDSHAPES + [JAW_RIGHT]
COLUMN_3_BLENDSHAPES = MOUTH_LEFT_BLENDSHAPES + [JAW_LEFT]
COLUMN_4_BLENDSHAPES = [BROW_INNER_UP, CHEEK_PUFF] + MOUTH_BOTH_BLENDSHAPES + [JAW_FORWARD, JAW_OPEN, TONGUE_OUT]

BLENDSHAPE_COLUMNS = [
    COLUMN_0_BLENDSHAPES,
    COLUMN_1_BLENDSHAPES,
    COLUMN_2_BLENDSHAPES,
    COLUMN_3_BLENDSHAPES,
    COLUMN_4_BLENDSHAPES,
]

RIGHT_EYE_BONE_X = "rightEyeBoneX"
RIGHT_EYE_BONE_Y = "rightEyeBoneX"
RIGHT_EYE_BONE_Z = "rightEyeBoneX"
RIGHT_EYE_BONE_ROTATIONS = [RIGHT_EYE_BONE_X, RIGHT_EYE_BONE_Y, RIGHT_EYE_BONE_Z]

LEFT_EYE_BONE_X = "leftEyeBoneX"
LEFT_EYE_BONE_Y = "leftEyeBoneY"
LEFT_EYE_BONE_Z = "leftEyeBoneZ"
LEFT_EYE_BONE_ROTATIONS = [LEFT_EYE_BONE_X, LEFT_EYE_BONE_Y, LEFT_EYE_BONE_Z]

HEAD_BONE_X = "headBoneX"
HEAD_BONE_Y = "headBoneY"
HEAD_BONE_Z = "headBoneZ"
HEAD_BONE_ROTATIONS = [HEAD_BONE_X, HEAD_BONE_Y, HEAD_BONE_Z]

ROTATION_NAMES = RIGHT_EYE_BONE_ROTATIONS + LEFT_EYE_BONE_ROTATIONS + HEAD_BONE_ROTATIONS

RIGHT_EYE_BONE_QUAT = "rightEyeBoneQuat"
LEFT_EYE_BONE_QUAT = "leftEyeBoneQuat"
HEAD_BONE_QUAT = "headBoneQuat"
QUATERNION_NAMES = [
    RIGHT_EYE_BONE_QUAT,
    LEFT_EYE_BONE_QUAT,
    HEAD_BONE_QUAT
]

IFACIALMOCAP_DATETIME_FORMAT = "%Y/%m/%d-%H:%M:%S.%f"
